export NAME="Bruno"
export SHORTDESC="Bruno the Jabber™ Bear"
export DESCRIPTION="Bruno is an Android XMPP/Jabber client with a clean user interface and open source (GPLv3)."
export HOMEPAGE="https://yaxim.org/bruno/"
export LOGO="https://yaxim.org/images/bruno-64.png"
export SCREENSHOT="https://yaxim.org/bruno/screenshots/bruno-roster-dark.png"
