<?xml version="1.0" encoding="utf-8"?>
<!-- yaxim version.xml AUTOGENERATED from version.xml.tpl -->
<resources>
<string name="build_revision">@build_revision@</string>
<string name="build_date">@build_date@</string>
<string name="build_version">@build_version@</string>
</resources>
