export NAME="yaxim"
export SHORTDESC="yet another XMPP instant messenger"
export DESCRIPTION="yaxim is an Android XMPP/Jabber client with a clean user interface and open source (GPLv3)."
export HOMEPAGE="https://yaxim.org/"
export LOGO="https://yaxim.org/images/yaxim.svg"
export SCREENSHOT="https://yaxim.org/screenshots/tiny/roster.png"
